//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipaksTestTask {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VipaksTestTask.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение будет закрыто..
        /// </summary>
        public static string AppWillBeClosed {
            get {
                return ResourceManager.GetString("AppWillBeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество пассажиров (Прилёт).
        /// </summary>
        public static string ArrivalCaption {
            get {
                return ResourceManager.GetString("ArrivalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибыло.
        /// </summary>
        public static string Arrived {
            get {
                return ResourceManager.GetString("Arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить расписание..
        /// </summary>
        public static string CanNotLoadSchedule {
            get {
                return ResourceManager.GetString("CanNotLoadSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за последние 24 часа.
        /// </summary>
        public static string DayPassengersCount {
            get {
                return ResourceManager.GetString("DayPassengersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество пассажиров (Вылет).
        /// </summary>
        public static string DepartureCaption {
            get {
                return ResourceManager.GetString("DepartureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убыло.
        /// </summary>
        public static string Departured {
            get {
                return ResourceManager.GetString("Departured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в последнем рейсе.
        /// </summary>
        public static string InLastFlight {
            get {
                return ResourceManager.GetString("InLastFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to прилёт из города {0} самолёт {1}, время {2}, кол-во пассажиров {3}.
        /// </summary>
        public static string LastArrivedPattern {
            get {
                return ResourceManager.GetString("LastArrivedPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вылет в город {0} самолёт {1}, время {2}, кол-во пассажиров {3}.
        /// </summary>
        public static string LastDeparturedPattern {
            get {
                return ResourceManager.GetString("LastDeparturedPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последний рейс:.
        /// </summary>
        public static string LastFlight {
            get {
                return ResourceManager.GetString("LastFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Множитель.
        /// </summary>
        public static string Multiplyer {
            get {
                return ResourceManager.GetString("Multiplyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн-табло.
        /// </summary>
        public static string OnlineScoreboard {
            get {
                return ResourceManager.GetString("OnlineScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание пустое..
        /// </summary>
        public static string SceduleIsEmpty {
            get {
                return ResourceManager.GetString("SceduleIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В расписании указан некорректный город..
        /// </summary>
        public static string ScheduleContainsInvalidCity {
            get {
                return ResourceManager.GetString("ScheduleContainsInvalidCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В расписании есть некорректное время рейса..
        /// </summary>
        public static string ScheduleContainsInvalidTime {
            get {
                return ResourceManager.GetString("ScheduleContainsInvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to всего.
        /// </summary>
        public static string TotalPassengersCount {
            get {
                return ResourceManager.GetString("TotalPassengersCount", resourceCulture);
            }
        }
    }
}
